package by.bsuir.bookmaker.service;

public enum CommandName {
    NO_SUCH_COMMAND,
    SIGN_IN_COMMAND,
    LOGOUT_COMMAND,
    REGISTER_COMMAND,
    CHANGE_LOCALE_COMMAND,
    GET_ALL_SPORT_TYPE_COMMAND,
    ADD_SPORT_TYPE_COMMAND,
    GET_ALL_PARTICIPANTS_COMMAND,
    ADD_PARTICIPANT_COMMAND,
    GET_ALL_TOURNAMENTS_COMMAND,
    ADD_TOURNAMENT_COMMAND,
    GET_ALL_BET_TYPE_COMMAND,
    GET_ALL_USERS_BET_COMMAND,
    GET_ALL_EVENTS_COMMAND,
    ADD_EVENT_COMMAND,
}
